// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMsAeGn8TNFwU6eNKqubnlYhYkYWTG9lE',
    appId: '1:823254850939:web:f926021a96be10b585b1de',
    messagingSenderId: '823254850939',
    projectId: 'foodies-907e0',
    authDomain: 'foodies-907e0.firebaseapp.com',
    storageBucket: 'foodies-907e0.appspot.com',
    measurementId: 'G-LNEN9XK10T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacM8Tiu9J5RZR6RMNq-I7_n3JYiuGvhY',
    appId: '1:823254850939:android:a6f0acf4ab6e358585b1de',
    messagingSenderId: '823254850939',
    projectId: 'foodies-907e0',
    storageBucket: 'foodies-907e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpOYK32n8xLoT3glr6ZktSIV47IDQvrag',
    appId: '1:823254850939:ios:7ab8af77ba89a65f85b1de',
    messagingSenderId: '823254850939',
    projectId: 'foodies-907e0',
    storageBucket: 'foodies-907e0.appspot.com',
    iosClientId: '823254850939-sf91ik9i93mielknartub2kl6qtqmtj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodiesRestaurent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpOYK32n8xLoT3glr6ZktSIV47IDQvrag',
    appId: '1:823254850939:ios:7ab8af77ba89a65f85b1de',
    messagingSenderId: '823254850939',
    projectId: 'foodies-907e0',
    storageBucket: 'foodies-907e0.appspot.com',
    iosClientId: '823254850939-sf91ik9i93mielknartub2kl6qtqmtj6.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodiesRestaurent',
  );
}
